import type { CompanyRecord, ContactRecord } from "../types";

export const mockCompanies: CompanyRecord[] = [
  { id: "co-1", name: "Apple", industry: "Technology", size: "201–500", revenue: "$25M–$50M", website: "www.apple.com", phone: "+1 (555) 123-0000", headquarters: "San Francisco, CA", owner: "Alex Morgan", status: "customer", tags: ["Enterprise", "Customer"], score: 85, deals: 8, dealValue: 42500, createdAt: "2024-01-15", notes: ["Expanding into the EMEA region.", "Discussed renewal partnership for Q3."] },
  { id: "co-2", name: "Google", industry: "Software", size: "501–1,000", revenue: "$10M–$25M", website: "www.google.com", phone: "+1 (555) 234-0000", headquarters: "Austin, TX", owner: "Priya Shah", status: "prospect", tags: ["SaaS", "Priority"], score: 78, deals: 5, dealValue: 28750, createdAt: "2024-02-08", notes: ["Security review scheduled with procurement."] },
  { id: "co-3", name: "Microsoft", industry: "IT Services", size: "51–200", revenue: "$5M–$10M", website: "www.microsoft.com", phone: "+1 (555) 345-0000", headquarters: "Dallas, TX", owner: "Alex Morgan", status: "prospect", tags: ["Mid-market"], score: 72, deals: 6, dealValue: 31000, createdAt: "2024-02-18", notes: ["Interested in consolidating support tooling."] },
  { id: "co-4", name: "Pfizer", industry: "Pharmaceuticals", size: "1,001–5,000", revenue: "$50M–$100M", website: "www.pfizer.com", phone: "+1 (555) 456-0000", headquarters: "Boston, MA", owner: "Priya Shah", status: "customer", tags: ["Enterprise", "Healthcare"], score: 91, deals: 4, dealValue: 54000, createdAt: "2024-03-04", notes: ["Annual security documentation is pending."] },
  { id: "co-5", name: "Tesla", industry: "Manufacturing", size: "5,000+", revenue: "$100M–$250M", website: "www.tesla.com", phone: "+1 (555) 567-0000", headquarters: "New York, NY", owner: "Alex Morgan", status: "partner", tags: ["Strategic", "Partner"], score: 94, deals: 7, dealValue: 98600, createdAt: "2024-03-20", notes: ["Joint innovation workshop planned."] },
  { id: "co-6", name: "Amazon", industry: "Conglomerate", size: "5,000+", revenue: "$250M+", website: "www.amazon.com", phone: "+1 (555) 678-0000", headquarters: "Gotham, NJ", owner: "Priya Shah", status: "customer", tags: ["Enterprise"], score: 89, deals: 6, dealValue: 74500, createdAt: "2024-04-11", notes: ["Executive business review in September."] },
  { id: "co-7", name: "Moderna", industry: "Biotechnology", size: "501–1,000", revenue: "$10M–$25M", website: "www.modernatx.com", phone: "+1 (555) 789-0000", headquarters: "New York, NY", owner: "Alex Morgan", status: "prospect", tags: ["Biotech"], score: 68, deals: 3, dealValue: 19400, createdAt: "2024-05-02", notes: ["Awaiting budget confirmation."] },
  { id: "co-8", name: "NVIDIA", industry: "Robotics", size: "201–500", revenue: "$5M–$10M", website: "www.nvidia.com", phone: "+1 (555) 890-0000", headquarters: "Los Angeles, CA", owner: "Priya Shah", status: "partner", tags: ["AI", "Partner"], score: 82, deals: 2, dealValue: 22000, createdAt: "2024-05-16", notes: ["Integration requirements shared."] },
];

export const mockContacts: ContactRecord[] = [
  { id: "ct-1", name: "John Carter", title: "Head of Sales", email: "john.carter@apple.com", phone: "+1 (555) 123-4567", companyId: "co-1", owner: "Alex Morgan", status: "customer", tags: ["Decision maker", "Sales"], lastContacted: "2h ago", createdAt: "2024-01-15", notes: ["Prefers concise weekly updates."] },
  { id: "ct-2", name: "Sarah Johnson", title: "Marketing Director", email: "sarah.j@google.com", phone: "+1 (555) 234-5678", companyId: "co-2", owner: "Priya Shah", status: "prospect", tags: ["Marketing"], lastContacted: "1d ago", createdAt: "2024-02-08", notes: ["Evaluating campaign attribution options."] },
  { id: "ct-3", name: "Michael Brown", title: "CTO", email: "michael@microsoft.com", phone: "+1 (555) 345-6789", companyId: "co-3", owner: "Alex Morgan", status: "prospect", tags: ["Technical", "Decision maker"], lastContacted: "2d ago", createdAt: "2024-02-18", notes: ["Requested an API architecture session."] },
  { id: "ct-4", name: "Emily Davis", title: "VP of Operations", email: "emily.d@pfizer.com", phone: "+1 (555) 456-7890", companyId: "co-4", owner: "Priya Shah", status: "customer", tags: ["Operations"], lastContacted: "3h ago", createdAt: "2024-03-04", notes: ["Renewal is on track."] },
  { id: "ct-5", name: "Daniel Wilson", title: "Sales Manager", email: "daniel@stark.com", phone: "+1 (555) 567-8901", companyId: "co-5", owner: "Alex Morgan", status: "partner", tags: ["Sales", "Champion"], lastContacted: "5h ago", createdAt: "2024-03-20", notes: ["Strong internal champion."] },
  { id: "ct-6", name: "Olivia Martinez", title: "Partnerships Lead", email: "olivia@amazon.com", phone: "+1 (555) 678-9012", companyId: "co-6", owner: "Priya Shah", status: "customer", tags: ["Partnerships"], lastContacted: "1d ago", createdAt: "2024-04-11", notes: ["Exploring a multi-year agreement."] },
  { id: "ct-7", name: "James Anderson", title: "Account Executive", email: "james@moderna.com", phone: "+1 (555) 789-0123", companyId: "co-7", owner: "Alex Morgan", status: "prospect", tags: ["Sales"], lastContacted: "4h ago", createdAt: "2024-05-02", notes: ["Budget owner joins next call."] },
  { id: "ct-8", name: "Charlotte White", title: "Product Manager", email: "charlotte@nvidia.com", phone: "+1 (555) 890-1234", companyId: "co-8", owner: "Priya Shah", status: "partner", tags: ["Product", "Technical"], lastContacted: "2d ago", createdAt: "2024-05-16", notes: ["Shared integration roadmap."] },
  { id: "ct-9", name: "Robert Fox", title: "Procurement Lead", email: "robert.fox@apple.com", phone: "+1 (555) 123-4588", companyId: "co-1", owner: "Alex Morgan", status: "customer", tags: ["Procurement"], lastContacted: "3d ago", createdAt: "2024-06-02", notes: ["Legal review due this month."] },
  { id: "ct-10", name: "Jenny Cooper", title: "VP Engineering", email: "jenny@google.com", phone: "+1 (555) 234-5699", companyId: "co-2", owner: "Priya Shah", status: "prospect", tags: ["Technical"], lastContacted: "5d ago", createdAt: "2024-06-18", notes: ["Needs SSO documentation."] },
  { id: "ct-11", name: "Cameron Lee", title: "Finance Director", email: "cameron@stark.com", phone: "+1 (555) 567-8933", companyId: "co-5", owner: "Alex Morgan", status: "partner", tags: ["Finance"], lastContacted: "1w ago", createdAt: "2024-07-03", notes: ["Requested pricing scenarios."] },
  { id: "ct-12", name: "Sophia Turner", title: "Research Lead", email: "sophia@moderna.com", phone: "+1 (555) 789-0155", companyId: "co-7", owner: "Priya Shah", status: "prospect", tags: ["Research"], lastContacted: "2w ago", createdAt: "2024-07-14", notes: ["Pilot scope under review."] },
];
