import type { AIConnector, ConnectorCategory } from "../types/connectors";

export const connectorCategories: { id: ConnectorCategory | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "communication", label: "Communication" },
  { id: "project-management", label: "Projects" },
  { id: "code", label: "Code" },
  { id: "calendar", label: "Calendar" },
  { id: "documents", label: "Docs" },
  { id: "crm", label: "CRM" },
  { id: "storage", label: "Storage" },
];

export const aiConnectors: AIConnector[] = [
  {
    id: "slack",
    name: "Slack",
    description: "Read channels, summarize threads, draft replies, and turn decisions into tasks.",
    category: "communication",
    status: "connected",
    syncState: "live",
    lastSynced: "2 min ago",
    objects: ["Channels", "Threads", "Mentions", "Decisions"],
    permissions: ["Read messages", "Draft replies", "Create reminders"],
    automations: ["Daily standup summary", "Escalate blocked work", "Create tasks from decisions"],
    gradient: "from-violet-500/30 via-fuchsia-500/20 to-sky-500/20",
  },
  {
    id: "jira",
    name: "Jira",
    description: "Understand epics, tickets, blockers, sprint scope, and delivery risk.",
    category: "project-management",
    status: "connected",
    syncState: "scheduled",
    lastSynced: "14 min ago",
    objects: ["Issues", "Epics", "Sprints", "Blockers"],
    permissions: ["Read issues", "Create issues", "Update status"],
    automations: ["Sprint risk brief", "Auto-create bugs", "Blocker triage"],
    gradient: "from-blue-500/30 via-indigo-500/20 to-cyan-500/20",
  },
  {
    id: "github",
    name: "GitHub",
    description: "Summarize pull requests, review code context, and connect commits to work items.",
    category: "code",
    status: "connected",
    syncState: "live",
    lastSynced: "Just now",
    objects: ["Repos", "PRs", "Issues", "Commits"],
    permissions: ["Read repos", "Read PRs", "Draft review notes"],
    automations: ["PR digest", "Release notes", "Code-to-ticket linking"],
    gradient: "from-zinc-500/30 via-slate-500/20 to-indigo-500/20",
  },
  {
    id: "google-calendar",
    name: "Google Calendar",
    description: "Find focus time, schedule meetings, detect conflicts, and protect deep work.",
    category: "calendar",
    status: "connected",
    syncState: "live",
    lastSynced: "4 min ago",
    objects: ["Events", "Attendees", "Availability", "Focus blocks"],
    permissions: ["Read calendar", "Create events", "Update events"],
    automations: ["Focus block planning", "Meeting prep", "Conflict detection"],
    gradient: "from-emerald-500/30 via-sky-500/20 to-blue-500/20",
  },
  {
    id: "google-meet",
    name: "Google Meet",
    description: "Prepare agendas, summarize calls, extract action items, and route follow-ups.",
    category: "communication",
    status: "available",
    syncState: "paused",
    lastSynced: "Not connected",
    objects: ["Meetings", "Transcripts", "Action items", "Participants"],
    permissions: ["Read transcripts", "Create summaries", "Share notes"],
    automations: ["Call summaries", "Follow-up emails", "Action item routing"],
    gradient: "from-green-500/30 via-teal-500/20 to-cyan-500/20",
  },
  {
    id: "gmail",
    name: "Gmail",
    description: "Summarize inboxes, draft responses, identify asks, and create follow-up tasks.",
    category: "communication",
    status: "needs_attention",
    syncState: "paused",
    lastSynced: "Auth expired",
    objects: ["Inbox", "Threads", "Labels", "Contacts"],
    permissions: ["Read email", "Draft email", "Create labels"],
    automations: ["Inbox briefing", "Reply drafts", "Follow-up detection"],
    gradient: "from-rose-500/30 via-orange-500/20 to-amber-500/20",
  },
  {
    id: "notion",
    name: "Notion",
    description: "Search docs, summarize decisions, and publish structured project updates.",
    category: "documents",
    status: "available",
    syncState: "paused",
    lastSynced: "Not connected",
    objects: ["Pages", "Databases", "Docs", "Decisions"],
    permissions: ["Read pages", "Create pages", "Update databases"],
    automations: ["Decision log", "Project status page", "Meeting notes"],
    gradient: "from-neutral-500/30 via-zinc-500/20 to-slate-500/20",
  },
  {
    id: "salesforce",
    name: "Salesforce",
    description: "Connect accounts, deals, contacts, tasks, and pipeline risk to the AI workspace.",
    category: "crm",
    status: "available",
    syncState: "paused",
    lastSynced: "Not connected",
    objects: ["Accounts", "Contacts", "Opportunities", "Activities"],
    permissions: ["Read CRM", "Create tasks", "Draft notes"],
    automations: ["Deal briefing", "Account research", "Next-best action"],
    gradient: "from-sky-500/30 via-blue-500/20 to-indigo-500/20",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    description: "Summarize contacts, companies, conversations, and sales follow-ups.",
    category: "crm",
    status: "available",
    syncState: "paused",
    lastSynced: "Not connected",
    objects: ["Contacts", "Companies", "Deals", "Conversations"],
    permissions: ["Read CRM", "Create notes", "Create tasks"],
    automations: ["Lead summary", "Pipeline hygiene", "Follow-up drafting"],
    gradient: "from-orange-500/30 via-amber-500/20 to-red-500/20",
  },
  {
    id: "google-drive",
    name: "Google Drive",
    description: "Search files, summarize documents, and attach context to projects and meetings.",
    category: "storage",
    status: "available",
    syncState: "paused",
    lastSynced: "Not connected",
    objects: ["Docs", "Sheets", "Slides", "Folders"],
    permissions: ["Read files", "Create docs", "Attach summaries"],
    automations: ["Doc search", "Brief generation", "Meeting packet"],
    gradient: "from-yellow-500/30 via-green-500/20 to-blue-500/20",
  },
  {
    id: "linear",
    name: "Linear",
    description: "Map issues, cycles, projects, and product work into a single AI context graph.",
    category: "project-management",
    status: "available",
    syncState: "paused",
    lastSynced: "Not connected",
    objects: ["Issues", "Projects", "Cycles", "Roadmaps"],
    permissions: ["Read issues", "Create issues", "Update status"],
    automations: ["Cycle summary", "Roadmap briefing", "Bug triage"],
    gradient: "from-indigo-500/30 via-violet-500/20 to-purple-500/20",
  },
  {
    id: "microsoft-teams",
    name: "Microsoft Teams",
    description: "Bring chats, meeting notes, mentions, and team decisions into Orion AI.",
    category: "communication",
    status: "available",
    syncState: "paused",
    lastSynced: "Not connected",
    objects: ["Chats", "Channels", "Calls", "Mentions"],
    permissions: ["Read messages", "Draft replies", "Create tasks"],
    automations: ["Channel digest", "Meeting recap", "Action item capture"],
    gradient: "from-purple-500/30 via-indigo-500/20 to-blue-500/20",
  },
];

export const connectorInsights = [
  "Slack mentions, Jira blockers, and GitHub PRs are linked into one daily priority brief.",
  "Google Calendar can reserve focus time automatically when urgent Jira tickets are detected.",
  "GitHub commits can be matched to Jira issues and summarized into release notes.",
  "Meeting notes can become tasks, follow-up emails, and CRM activity logs in one flow.",
];

export const connectorPlaybooks = [
  {
    title: "Daily command briefing",
    description: "Summarize Slack, Jira, GitHub, Calendar, and Email into one morning plan.",
    connectors: ["Slack", "Jira", "GitHub", "Calendar", "Gmail"],
  },
  {
    title: "Meeting to execution",
    description: "Turn Meet transcripts into Jira tickets, Slack follow-ups, and calendar reminders.",
    connectors: ["Google Meet", "Jira", "Slack", "Calendar"],
  },
  {
    title: "Release readiness",
    description: "Combine GitHub PRs, Linear/Jira scope, and docs into a launch checklist.",
    connectors: ["GitHub", "Jira", "Linear", "Notion"],
  },
];