"use client";

import { useState } from "react";
import { CalendarDays, CheckCircle2, ChevronDown, CircleDollarSign, Download, FileSpreadsheet, FileText, Filter, Goal, Trophy, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { cn } from "@/shared/lib/utils";

const tabs = ["Overview", "Leads", "Deals", "Activities", "Sales", "Performance", "Custom Reports"] as const;
const sourceData = [["Website", 35, "#7566e8"], ["Referrals", 25, "#2687dc"], ["Social Media", 20, "#23b99a"], ["Email Campaign", 12, "#e8a522"], ["Others", 8, "#db6575"]] as const;
const stageData = [["New", 460, "100%", "$231,000", "#7566e8"], ["Qualified", 310, "67%", "$186,500", "#2e82dc"], ["Proposal", 178, "38%", "$94,200", "#15a485"], ["Negotiation", 92, "20%", "$62,780", "#e5a225"], ["Closed Won", 98, "21%", "$125,430", "#de6376"], ["Closed Lost", 44, "10%", "$18,320", "#60708d"]] as const;
const recent = [["New lead created", "John Doe from Acme Corp", "2m ago", UsersRound, "#7566e8"], ["Deal won", "Enterprise Plan · $12,000", "15m ago", Trophy, "#2e82dc"], ["Task completed", "Follow up call with Sarah", "1h ago", CheckCircle2, "#23b99a"], ["Contact updated", "Michael Brown", "2h ago", UsersRound, "#e5a225"]] as const;

function Panel({ title, action, children }: { title: string; action?: React.ReactNode; children: React.ReactNode }) { return <section className="orion-panel min-w-0 overflow-hidden"><header className="flex items-center justify-between border-b border-border/70 px-3.5 py-2.5"><h2 className="text-[10px] font-semibold text-foreground">{title}</h2>{action}</header>{children}</section>; }
function Metric({ label, value, delta, icon: Icon, color }: { label: string; value: string; delta: string; icon: typeof Goal; color: string }) { return <article className="orion-panel p-3"><div className="flex justify-between"><div><p className="text-[10px] text-muted-foreground">{label}</p><p className="mt-1 text-[21px] font-semibold text-foreground">{value}</p></div><span className="grid h-7 w-7 place-items-center rounded-full" style={{ color, backgroundColor: `${color}18` }}><Icon className="h-3.5 w-3.5" /></span></div><p className="mt-1.5 text-[9px] text-success">↑ {delta}<span className="text-muted-foreground"> vs last period</span></p></article>; }

export function ReportsWorkspace() {
  const [tab, setTab] = useState<(typeof tabs)[number]>("Overview"); const [filters, setFilters] = useState(false); const [range, setRange] = useState(false);
  const exports = [[FileText, "PDF", "#ef5964"], [FileSpreadsheet, "Excel", "#29af79"], [Download, "CSV", "#e5a225"]] as const;
  return <div className="space-y-3"><header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-xl font-semibold tracking-tight text-foreground">Reports</h1><p className="mt-0.5 text-[11px] text-muted-foreground">Track performance, analyze trends, and make data-driven decisions.</p></div><div className="flex gap-2"><div className="relative"><button type="button" onClick={() => setRange(!range)} className="orion-glass-control flex h-8 items-center gap-1.5 rounded-lg px-3 text-[10px]"><CalendarDays className="h-3.5 w-3.5" />May 26 – June 1, 2024<ChevronDown className="h-3 w-3" /></button>{range ? <div className="absolute right-0 top-10 z-30 w-48 rounded-xl border border-border bg-popover p-1.5 shadow-floating"><button className="w-full rounded-lg px-2 py-2 text-left text-[10px] hover:bg-primary/10" onClick={() => setRange(false)}>Last 7 days</button><button className="w-full rounded-lg px-2 py-2 text-left text-[10px] hover:bg-primary/10" onClick={() => setRange(false)}>This month</button></div> : null}</div><div className="relative"><button type="button" onClick={() => setFilters(!filters)} className="orion-glass-control flex h-8 items-center gap-1.5 rounded-lg px-3 text-[10px]"><Filter className="h-3.5 w-3.5" />Filters<ChevronDown className="h-3 w-3" /></button>{filters ? <div className="absolute right-0 top-10 z-30 w-44 rounded-xl border border-border bg-popover p-2 shadow-floating"><button className="block w-full rounded-lg px-2 py-2 text-left text-[10px] hover:bg-primary/10" onClick={() => { setFilters(false); toast.success("Owner filter applied"); }}>All owners</button><button className="block w-full rounded-lg px-2 py-2 text-left text-[10px] hover:bg-primary/10" onClick={() => { setFilters(false); toast.success("Pipeline filter applied"); }}>All pipelines</button></div> : null}</div></div></header>
    <nav className="flex overflow-x-auto border-b border-border">{tabs.map((item) => <button key={item} onClick={() => { setTab(item); if (item !== "Overview") toast.info(`${item} report selected`); }} className={cn("shrink-0 border-b-2 px-3 py-2 text-[9px]", tab === item ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground")}>{item}</button>)}</nav>
    <div className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_230px]"><main className="min-w-0 space-y-3"><section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Total Leads" value="1,250" delta="18.6%" icon={UsersRound} color="#7566e8" /><Metric label="Open Deals" value="320" delta="12.4%" icon={Goal} color="#2e82dc" /><Metric label="Won Deals" value="98" delta="24.8%" icon={CheckCircle2} color="#23b99a" /><Metric label="Revenue" value="$125,430" delta="16.7%" icon={CircleDollarSign} color="#e5a225" /></section>
      <section className="grid gap-3 lg:grid-cols-2"><Panel title="Leads Over Time" action={<span className="text-[9px] text-muted-foreground">Weekly <ChevronDown className="inline h-3 w-3" /></span>}><div className="h-[170px] p-4"><svg viewBox="0 0 400 150" className="h-full w-full"><g stroke="currentColor" className="text-border/50">{[20,50,80,110,140].map(y => <line key={y} x1="0" x2="400" y1={y} y2={y} />)}</g><polyline points="10,108 100,82 190,67 280,62 370,35" fill="none" stroke="#7566e8" strokeWidth="3" />{[[10,108,"850"],[100,82,"980"],[190,67,"1,060"],[280,62,"1,080"],[370,35,"1,250"]].map(([x,y,label]) => <g key={String(label)}><circle cx={Number(x)} cy={Number(y)} r="4" fill="#0b141c" stroke="#9a8efa" strokeWidth="2" /><text x={Number(x)} y={Number(y)-10} textAnchor="middle" className="fill-foreground text-[10px]">{label}</text></g>)}</svg><div className="flex justify-between text-[8px] text-muted-foreground"><span>Apr 28</span><span>May 5</span><span>May 12</span><span>May 19</span><span>Jun 1</span></div></div></Panel><Panel title="Leads by Source" action={<button onClick={() => toast.info("Source report opened")} className="text-[9px] text-primary">View full report</button>}><div className="flex items-center gap-5 p-4"><div className="relative grid h-28 w-28 shrink-0 place-items-center rounded-full" style={{ background: "conic-gradient(#7566e8 0 35%,#2687dc 35% 60%,#23b99a 60% 80%,#e8a522 80% 92%,#db6575 92%)" }}><div className="grid h-[70px] w-[70px] place-items-center rounded-full bg-[#0b141c] text-center text-[9px] text-muted-foreground"><b className="block text-lg text-foreground">1,250</b>Total</div></div><div className="flex-1 space-y-2">{sourceData.map(([name, value, color]) => <div key={name} className="flex gap-2 text-[9px]"><span className="mt-1 h-1.5 w-1.5 rounded-full" style={{ backgroundColor: color }} /><span className="flex-1 text-muted-foreground">{name}</span><span>{value}% ({value * 12.5})</span></div>)}</div></div></Panel></section>
      <section className="grid gap-3 lg:grid-cols-[1.05fr_1fr]"><Panel title="Deals by Stage"><div className="grid grid-cols-[90px_1fr] gap-3 p-3 text-[8px]"><div className="space-y-1.5 pt-5">{stageData.map(([, , , ,color], i) => <div key={color} className="h-4 rounded-sm" style={{ width: `${100-i*10}%`, backgroundColor: color }} />)}</div><div><div className="grid grid-cols-[1fr_28px_44px_52px] gap-2 border-b border-border pb-2 text-muted-foreground"><span>Stage</span><span>Deals</span><span>Conv.</span><span>Value</span></div><div className="mt-2 space-y-2">{stageData.map(([name,deals,conversion,value,color]) => <div key={name} className="grid grid-cols-[1fr_28px_44px_52px] gap-2"><span><i className="mr-1 inline-block h-1.5 w-1.5 rounded-full" style={{ backgroundColor: color }} />{name}</span><span>{deals}</span><span>{conversion}</span><span>{value}</span></div>)}</div></div></div></Panel><Panel title="Revenue Over Time" action={<span className="text-[9px] text-muted-foreground">Monthly <ChevronDown className="inline h-3 w-3" /></span>}><div className="flex h-[175px] items-end gap-3 px-5 pb-5 pt-7">{[78,86,95,106,115,125].map((value,i) => <div key={value} className="flex h-full flex-1 flex-col justify-end"><span className="mb-1 text-center text-[8px]">${value}K</span><div className="rounded-t-sm bg-[#7566e8]/80" style={{ height: `${value/1.35}%` }} /><span className="mt-2 text-center text-[8px] text-muted-foreground">{["Jan","Feb","Mar","Apr","May","Jun"][i]}</span></div>)}</div></Panel></section></main>
      <aside className="space-y-3"><Panel title="Recent Activity" action={<button className="text-[9px] text-primary">View all</button>}><div className="space-y-3 p-3">{recent.map(([title,detail,time,Icon,color]) => <button key={title} onClick={() => toast.info(title)} className="flex w-full gap-2 text-left"><span className="grid h-5 w-5 place-items-center rounded-md" style={{ color, backgroundColor: `${color}20` }}><Icon className="h-3 w-3" /></span><span className="min-w-0 flex-1"><b className="block text-[9px] font-normal text-foreground">{title}</b><span className="block truncate text-[8px] text-muted-foreground">{detail}</span></span><small className="text-[8px] text-muted-foreground">{time}</small></button>)}</div></Panel><Panel title="Top Deals by Value" action={<button className="text-[9px] text-primary">View all</button>}><ol className="space-y-2.5 p-3">{[["Acme Corporation","$25,000"],["Custom Integration","$18,750"],["Premium Support","$15,600"],["Annual Subscription","$12,300"],["Data Migration","$9,850"]].map(([name,value],i) => <li key={name} className="flex items-center gap-2"><span className="grid h-5 w-5 place-items-center rounded-full bg-foreground/[0.06] text-[8px] text-muted-foreground">{i+1}</span><span className="flex-1 text-[9px] text-foreground">{name}</span><b className="text-[8px] text-success">{value}</b></li>)}</ol></Panel><Panel title="Download Reports"><div className="grid grid-cols-3 gap-2 p-3">{exports.map(([Icon,label,color]) => <button key={label} onClick={() => toast.success(`${label} report is being prepared`)} className="flex flex-col items-center gap-1 rounded-lg border border-border py-2 text-[8px] text-muted-foreground hover:border-primary/30"><Icon className="h-4 w-4" style={{ color }} />{label}</button>)}</div></Panel></aside></div></div>;
}
