"use client";

import { useMemo, useState } from "react";
import { CalendarDays, CheckCircle2, ChevronDown, CircleDollarSign, Download, FileSpreadsheet, FileText, Filter, Goal, Trophy, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { cn } from "@/shared/lib/utils";

const tabs = ["Overview", "Leads", "Deals", "Activities", "Sales", "Performance", "Custom Reports"] as const;
const ranges = ["May 26 – June 1, 2024", "May 19 – May 25, 2024", "May 1 – May 31, 2024"];
const sourceData = [["Website", 35, "#7566e8"], ["Referrals", 25, "#2687dc"], ["Social Media", 20, "#23b99a"], ["Email Campaign", 12, "#e8a522"], ["Others", 8, "#db6575"]] as const;
const stages = [["New", 460, "100%", "$231,000", "#7566e8"], ["Qualified", 310, "67%", "$186,500", "#2e82dc"], ["Proposal", 178, "38%", "$94,200", "#15a485"], ["Negotiation", 92, "20%", "$62,780", "#e5a225"], ["Closed Won", 98, "21%", "$125,430", "#de6376"], ["Closed Lost", 44, "10%", "$18,320", "#60708d"]] as const;

function Panel({ title, action, children }: { title: string; action?: React.ReactNode; children: React.ReactNode }) { return <section className="orion-panel min-w-0 overflow-hidden"><header className="flex items-center justify-between border-b border-border/70 px-4 py-3"><h2 className="text-xs font-semibold text-foreground">{title}</h2>{action}</header>{children}</section>; }
function Metric({ label, value, icon: Icon, color, onClick }: { label: string; value: string; icon: typeof Goal; color: string; onClick: () => void }) { return <button type="button" onClick={onClick} className="orion-panel p-4 text-left transition hover:border-primary/30"><div className="flex justify-between"><div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold text-foreground">{value}</p></div><span className="grid h-9 w-9 place-items-center rounded-full" style={{ color, backgroundColor: `${color}18` }}><Icon className="h-4 w-4" /></span></div><p className="mt-2 text-[10px] text-success">↑ 12.4% <span className="text-muted-foreground">vs last period</span></p></button>; }
function downloadCsv(name: string, tab: string, period: string) { const content = `Report,${tab}\nPeriod,${period}\nGenerated,${new Date().toISOString()}\n\nMetric,Value\nTotal Leads,1250\nOpen Deals,320\nWon Deals,98\nRevenue,125430\n`; const url = URL.createObjectURL(new Blob([content], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = `${name.toLowerCase()}-${tab.toLowerCase().replaceAll(" ", "-")}.csv`; link.click(); URL.revokeObjectURL(url); }

export function ReportsWorkspace() {
  const [tab, setTab] = useState<(typeof tabs)[number]>("Overview");
  const [period, setPeriod] = useState(ranges[0]);
  const [rangeOpen, setRangeOpen] = useState(false);
  const [filterOpen, setFilterOpen] = useState(false);
  const [owner, setOwner] = useState("All owners");
  const [pipeline, setPipeline] = useState("All pipelines");
  const [detail, setDetail] = useState<string | null>(null);
  const filteredTotal = useMemo(() => owner === "All owners" && pipeline === "All pipelines" ? "1,250" : owner === "Alex Morgan" ? "740" : "510", [owner, pipeline]);
  const selectTab = (next: (typeof tabs)[number]) => { setTab(next); setDetail(next === "Overview" ? null : next); };
  const showDetail = (name: string) => { setDetail(name); toast.info(`${name} report selected`); };
  return <div className="space-y-4"><header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight text-foreground">Reports</h1><p className="mt-1 text-sm text-muted-foreground">Track performance, analyze trends, and make data-driven decisions.</p></div><div className="flex gap-2"><div className="relative"><button type="button" onClick={() => setRangeOpen(!rangeOpen)} className="orion-glass-control flex h-10 items-center gap-2 rounded-xl px-4 text-sm text-foreground"><CalendarDays className="h-4 w-4" />{period}<ChevronDown className="h-4 w-4" /></button>{rangeOpen ? <div className="absolute right-0 top-12 z-30 w-56 rounded-xl border border-border bg-popover p-2 shadow-floating">{ranges.map((item) => <button key={item} type="button" onClick={() => { setPeriod(item); setRangeOpen(false); toast.success(`Reporting period set to ${item}`); }} className={cn("block w-full rounded-lg px-3 py-2.5 text-left text-xs", item === period ? "bg-primary/10 text-primary" : "text-foreground hover:bg-foreground/[0.06]")}>{item}</button>)}</div> : null}</div><div className="relative"><button type="button" onClick={() => setFilterOpen(!filterOpen)} className="orion-glass-control flex h-10 items-center gap-2 rounded-xl px-4 text-sm text-foreground"><Filter className="h-4 w-4" />Filters<ChevronDown className="h-4 w-4" /></button>{filterOpen ? <div className="absolute right-0 top-12 z-30 w-60 rounded-xl border border-border bg-popover p-3 shadow-floating"><label className="block text-[10px] text-muted-foreground">Owner<select value={owner} onChange={(e) => setOwner(e.target.value)} className="orion-glass-control mt-1.5 h-9 w-full rounded-lg px-2 text-xs text-foreground"><option>All owners</option><option>Alex Morgan</option><option>Priya Shah</option></select></label><label className="mt-3 block text-[10px] text-muted-foreground">Pipeline<select value={pipeline} onChange={(e) => setPipeline(e.target.value)} className="orion-glass-control mt-1.5 h-9 w-full rounded-lg px-2 text-xs text-foreground"><option>All pipelines</option><option>Enterprise</option><option>Commercial</option></select></label><div className="mt-3 flex justify-between"><button type="button" onClick={() => { setOwner("All owners"); setPipeline("All pipelines"); }} className="text-xs text-muted-foreground">Reset</button><button type="button" onClick={() => { setFilterOpen(false); toast.success("Filters applied"); }} className="text-xs text-primary">Apply filters</button></div></div> : null}</div></div></header>
    <nav className="flex overflow-x-auto border-b border-border" aria-label="Report categories">{tabs.map((item) => <button key={item} type="button" onClick={() => selectTab(item)} className={cn("shrink-0 border-b-2 px-5 py-3.5 text-sm font-medium", tab === item ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground")}>{item}</button>)}</nav>
    {detail ? <div className="orion-panel flex items-center justify-between p-4"><div><p className="text-sm font-semibold text-foreground">{detail} report</p><p className="mt-1 text-xs text-muted-foreground">Focused report view for {period} · {owner} · {pipeline}</p></div><button type="button" onClick={() => setDetail(null)} className="rounded-lg border border-border px-3 py-2 text-xs text-foreground">Back to overview</button></div> : null}
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_270px]"><main className="min-w-0 space-y-4"><section className="grid grid-cols-2 gap-4 lg:grid-cols-4"><Metric label="Total Leads" value={filteredTotal} icon={UsersRound} color="#7566e8" onClick={() => showDetail("Leads")} /><Metric label="Open Deals" value={pipeline === "Enterprise" ? "182" : "320"} icon={Goal} color="#2e82dc" onClick={() => showDetail("Deals")} /><Metric label="Won Deals" value="98" icon={CheckCircle2} color="#23b99a" onClick={() => showDetail("Sales")} /><Metric label="Revenue" value="$125,430" icon={CircleDollarSign} color="#e5a225" onClick={() => showDetail("Revenue")} /></section>
      <section className="grid gap-4 lg:grid-cols-2"><Panel title="Leads Over Time" action={<button onClick={() => showDetail("Leads over time")} className="text-xs text-primary">View report</button>}><div className="h-[220px] p-5"><svg viewBox="0 0 400 160" className="h-full w-full"><g stroke="currentColor" className="text-border/50">{[20,55,90,125,150].map(y => <line key={y} x1="0" x2="400" y1={y} y2={y} />)}</g><polyline points="12,120 102,91 192,75 282,68 372,36" fill="none" stroke="#19d7c0" strokeWidth="3" />{[12,102,192,282,372].map((x, i) => <circle key={x} cx={x} cy={[120,91,75,68,36][i]} r="4" fill="#0b141c" stroke="#19d7c0" strokeWidth="2" />)}</svg><div className="flex justify-between text-[9px] text-muted-foreground"><span>Apr 28</span><span>May 5</span><span>May 12</span><span>May 19</span><span>Jun 1</span></div></div></Panel><Panel title="Leads by Source" action={<button onClick={() => showDetail("Lead sources")} className="text-xs text-primary">View full report</button>}><div className="flex items-center gap-6 p-5"><div className="relative grid h-32 w-32 shrink-0 place-items-center rounded-full" style={{ background: "conic-gradient(#7566e8 0 35%,#2687dc 35% 60%,#23b99a 60% 80%,#e8a522 80% 92%,#db6575 92%)" }}><div className="grid h-20 w-20 place-items-center rounded-full bg-[#0b141c] text-center text-[10px] text-muted-foreground"><b className="block text-xl text-foreground">{filteredTotal}</b>Total</div></div><div className="flex-1 space-y-3">{sourceData.map(([name, value, color]) => <button key={name} onClick={() => showDetail(name)} className="flex w-full gap-2 text-left text-xs"><span className="mt-1.5 h-2 w-2 rounded-full" style={{ backgroundColor: color }} /><span className="flex-1 text-muted-foreground">{name}</span><span className="text-foreground">{value}%</span></button>)}</div></div></Panel></section>
      <section className="grid gap-4 lg:grid-cols-[1.05fr_1fr]"><Panel title="Deals by Stage"><div className="space-y-3 p-4">{stages.map(([name,deals,conversion,value,color]) => <button key={name} onClick={() => showDetail(name)} className="grid w-full grid-cols-[1fr_42px_52px_70px] items-center gap-3 text-left text-xs"><span className="flex items-center gap-2 text-foreground"><i className="h-2 w-2 rounded-full" style={{ backgroundColor: color }} />{name}</span><span className="text-muted-foreground">{deals}</span><span className="text-muted-foreground">{conversion}</span><span className="text-right font-medium text-foreground">{value}</span></button>)}</div></Panel><Panel title="Revenue Over Time"><div className="flex h-[220px] items-end gap-4 px-6 pb-7 pt-8">{[78,86,95,106,115,125].map((value,i) => <button key={value} onClick={() => showDetail(`${["Jan","Feb","Mar","Apr","May","Jun"][i]} revenue`)} className="flex h-full flex-1 flex-col justify-end"><span className="mb-2 text-center text-[10px] text-foreground">${value}K</span><span className="rounded-t-sm bg-primary/80 transition hover:bg-primary" style={{ height: `${value/1.35}%` }} /><span className="mt-2 text-center text-[10px] text-muted-foreground">{["Jan","Feb","Mar","Apr","May","Jun"][i]}</span></button>)}</div></Panel></section></main>
      <aside className="space-y-4"><Panel title="Recent Activity" action={<button onClick={() => showDetail("Activity")} className="text-xs text-primary">View all</button>}><div className="space-y-4 p-4">{[["New lead created","John Doe from Acme Corp","2m ago",UsersRound],["Deal won","Enterprise Plan · $12,000","15m ago",Trophy],["Task completed","Follow up call with Sarah","1h ago",CheckCircle2],["Contact updated","Michael Brown","2h ago",UsersRound],["Payment received","Invoice #INV-001","3h ago",CircleDollarSign]].map(([title,detail,time,Icon]) => { const ActivityIcon = Icon as typeof UsersRound; return <button key={title as string} onClick={() => showDetail(title as string)} className="flex w-full gap-2 text-left"><span className="grid h-7 w-7 place-items-center rounded-lg bg-primary/10 text-primary"><ActivityIcon className="h-4 w-4" /></span><span className="min-w-0 flex-1"><b className="block text-xs font-medium text-foreground">{title as string}</b><span className="block truncate text-[10px] text-muted-foreground">{detail as string}</span></span><small className="text-[9px] text-muted-foreground">{time as string}</small></button>; })}</div></Panel><Panel title="Top Deals by Value" action={<button onClick={() => showDetail("Top deals")} className="text-xs text-primary">View all</button>}><ol className="space-y-3 p-4">{[["Enterprise Plan","Acme Corporation","$25,000"],["Custom Integration","Globex Inc.","$18,750"],["Premium Support","Initech","$15,600"],["Annual Subscription","Soylent Corp.","$12,300"],["Data Migration","Umbrella Corp.","$9,850"]].map(([title,company,value], index) => <li key={title} className="flex items-center gap-2.5"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-md bg-primary/10 text-[10px] font-semibold text-primary">{index + 1}</span><button type="button" onClick={() => showDetail(title)} className="min-w-0 flex-1 text-left"><b className="block truncate text-xs font-medium text-foreground">{title}</b><span className="block truncate text-[10px] text-muted-foreground">{company}</span></button><span className="text-xs font-semibold text-success">{value}</span></li>)}</ol></Panel><Panel title="Download Reports"><div className="grid grid-cols-3 gap-2 p-4">{[[FileText,"PDF","#ef5964"],[FileSpreadsheet,"Excel","#29af79"],[Download,"CSV","#e5a225"]].map(([Icon,label,color]) => { const ExportIcon = Icon as typeof Download; return <button key={label as string} onClick={() => { downloadCsv(label as string, tab, period); toast.success(`${label as string} export downloaded`); }} className="flex flex-col items-center gap-1.5 rounded-lg border border-border py-3 text-[10px] text-muted-foreground hover:border-primary/30"><ExportIcon className="h-5 w-5" style={{ color: color as string }} />{label as string}</button>; })}</div></Panel></aside></div></div>;
}
