import type { McpServer } from "../types";

export const mcpServers: McpServer[] = [
  {
    id: "github",
    name: "GitHub",
    description: "Repos, pull requests, issues, and Actions over the official GitHub MCP server.",
    transport: "http",
    status: "connected",
    auth: "oauth",
    endpoint: "https://api.githubcopilot.com/mcp/",
    tools: 35,
    resources: 4,
    prompts: 2,
  },
  {
    id: "linear",
    name: "Linear",
    description: "Issues, cycles, projects, and roadmaps from your Linear workspace.",
    transport: "http",
    status: "connected",
    auth: "oauth",
    endpoint: "https://mcp.linear.app/mcp",
    tools: 16,
    resources: 2,
    prompts: 3,
  },
  {
    id: "filesystem",
    name: "Filesystem",
    description: "Read, write, and search files in a sandboxed local directory.",
    transport: "stdio",
    status: "connected",
    auth: "none",
    endpoint: "npx -y @modelcontextprotocol/server-filesystem /workspace",
    tools: 11,
    resources: 0,
    prompts: 0,
  },
  {
    id: "postgres",
    name: "PostgreSQL",
    description: "Run read-only SQL and expose table schemas as resources.",
    transport: "stdio",
    status: "connected",
    auth: "none",
    endpoint: "npx -y @modelcontextprotocol/server-postgres",
    tools: 1,
    resources: 12,
    prompts: 0,
  },
  {
    id: "notion",
    name: "Notion",
    description: "Search pages and databases, read docs, and publish project updates.",
    transport: "http",
    status: "available",
    auth: "oauth",
    endpoint: "https://mcp.notion.com/mcp",
    tools: 14,
    resources: 5,
    prompts: 2,
  },
  {
    id: "sentry",
    name: "Sentry",
    description: "Inspect issues, events, and release health for connected projects.",
    transport: "http",
    status: "available",
    auth: "oauth",
    endpoint: "https://mcp.sentry.dev/mcp",
    tools: 9,
    resources: 3,
    prompts: 1,
  },
  {
    id: "stripe",
    name: "Stripe",
    description: "Query customers, payments, invoices, and subscriptions.",
    transport: "http",
    status: "available",
    auth: "bearer",
    endpoint: "https://mcp.stripe.com",
    tools: 18,
    resources: 0,
    prompts: 2,
  },
  {
    id: "puppeteer",
    name: "Puppeteer",
    description: "Drive a headless browser — navigate, click, screenshot, and scrape.",
    transport: "stdio",
    status: "available",
    auth: "none",
    endpoint: "npx -y @modelcontextprotocol/server-puppeteer",
    tools: 7,
    resources: 2,
    prompts: 0,
  },
  {
    id: "memory",
    name: "Memory",
    description: "A persistent knowledge-graph store the assistant can read and update.",
    transport: "stdio",
    status: "available",
    auth: "none",
    endpoint: "npx -y @modelcontextprotocol/server-memory",
    tools: 9,
    resources: 1,
    prompts: 0,
  },
  {
    id: "slack",
    name: "Slack",
    description: "Read channels, summarize threads, and post messages over MCP.",
    transport: "sse",
    status: "available",
    auth: "oauth",
    endpoint: "https://mcp.slack.example/sse",
    tools: 8,
    resources: 3,
    prompts: 1,
  },
];
