import type { Task } from "@/shared/types";

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Review design system tokens",
    description: "Verify all color and spacing tokens match the Figma designs",
    status: "in_progress",
    priority: "high",
    tags: ["design", "urgent"],
    dueDate: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Implement command palette shortcuts",
    description: "Add keyboard shortcuts for all navigation actions",
    status: "todo",
    priority: "medium",
    tags: ["feature"],
    dueDate: new Date(Date.now() + 172800000).toISOString(),
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Write API documentation",
    description: "Document all REST endpoints for the backend",
    status: "todo",
    priority: "low",
    tags: ["docs"],
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Fix sidebar animation jank",
    description: "The sidebar transition stutters on slower devices",
    status: "done",
    priority: "high",
    tags: ["bug", "ui"],
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "5",
    title: "Set up CI/CD pipeline",
    description: "Configure GitHub Actions for automated testing and deployment",
    status: "in_progress",
    priority: "urgent",
    tags: ["devops"],
    dueDate: new Date(Date.now() + 43200000).toISOString(),
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    title: "Migrate to Tailwind v4",
    description: "Update configuration and fix breaking changes",
    status: "todo",
    priority: "medium",
    tags: ["refactor"],
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "7",
    title: "Add email notification preferences",
    description: "Let users choose which emails they want to receive",
    status: "todo",
    priority: "low",
    tags: ["feature", "settings"],
    createdAt: new Date(Date.now() - 518400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "8",
    title: "Performance audit",
    description: "Run Lighthouse and optimize critical rendering path",
    status: "done",
    priority: "medium",
    tags: ["performance"],
    createdAt: new Date(Date.now() - 604800000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
];
