import type { Task, User } from "@/shared/types";

const alex: User = {
  id: "u1",
  name: "Alex Kim",
  email: "alex@orion.dev",
  role: "admin",
};

const jordan: User = {
  id: "u2",
  name: "Jordan Lee",
  email: "jordan@orion.dev",
  role: "member",
};

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Verify all color and spacing tokens",
    description: "Verify all color and spacing tokens match the Figma designs",
    notes:
      "Audit the entire design system and ensure consistency across all components.",
    status: "in_progress",
    priority: "high",
    tags: ["design", "urgent"],
    assignee: alex,
    dueDate: "2026-07-01T09:00:00.000Z",
    subtasks: [
      { id: "1a", title: "Verify color tokens", done: true },
      { id: "1b", title: "Check spacing tokens", done: true },
      { id: "1c", title: "Validate typography scale", done: false },
      { id: "1d", title: "Test component variants", done: false },
    ],
    createdAt: "2026-06-24T09:00:00.000Z",
    updatedAt: "2026-06-26T09:00:00.000Z",
  },
  {
    id: "2",
    title: "Implement command palette shortcuts",
    description: "Add keyboard shortcuts for all navigation actions",
    notes: "Map every primary route to a Ctrl/Cmd chord and document them.",
    status: "todo",
    priority: "medium",
    tags: ["feature"],
    assignee: alex,
    dueDate: "2026-06-28T09:00:00.000Z",
    subtasks: [
      { id: "2a", title: "Register global hotkeys", done: false },
      { id: "2b", title: "Add palette search", done: false },
    ],
    createdAt: "2026-06-25T09:00:00.000Z",
    updatedAt: "2026-06-26T09:00:00.000Z",
  },
  {
    id: "3",
    title: "Write API documentation",
    description: "Document all REST endpoints for the backend",
    notes: "Cover auth, tasks, calendar, and email resources with examples.",
    status: "todo",
    priority: "low",
    tags: ["docs"],
    assignee: jordan,
    createdAt: "2026-06-23T09:00:00.000Z",
    updatedAt: "2026-06-26T09:00:00.000Z",
  },
  {
    id: "4",
    title: "Fix sidebar animation jank",
    description: "The sidebar transition stutters on slower devices",
    notes: "Profile the transition and move to GPU-accelerated transforms.",
    status: "done",
    priority: "high",
    tags: ["bug", "ui"],
    assignee: alex,
    saved: true,
    subtasks: [
      { id: "4a", title: "Profile transition", done: true },
      { id: "4b", title: "Switch to transform", done: true },
    ],
    createdAt: "2026-06-22T09:00:00.000Z",
    updatedAt: "2026-06-26T08:00:00.000Z",
  },
  {
    id: "5",
    title: "Set up CI/CD pipeline",
    description: "Configure GitHub Actions for automated testing and deploy...",
    notes: "Run lint, typecheck, and tests on every PR before deploy.",
    status: "in_progress",
    priority: "urgent",
    tags: ["devops"],
    assignee: jordan,
    dueDate: "2026-06-27T21:00:00.000Z",
    subtasks: [
      { id: "5a", title: "Add lint + test workflow", done: true },
      { id: "5b", title: "Configure preview deploys", done: false },
      { id: "5c", title: "Add production gate", done: false },
    ],
    createdAt: "2026-06-25T09:00:00.000Z",
    updatedAt: "2026-06-26T09:00:00.000Z",
  },
  {
    id: "6",
    title: "Migrate to Tailwind v4",
    description: "Update configuration and fix breaking changes",
    notes: "Move theme tokens to @theme and remove the legacy config.",
    status: "todo",
    priority: "medium",
    tags: ["refactor"],
    assignee: alex,
    createdAt: "2026-06-21T09:00:00.000Z",
    updatedAt: "2026-06-26T09:00:00.000Z",
  },
  {
    id: "7",
    title: "Add email notification preferences",
    description: "Let users choose which emails they want to receive",
    notes: "Add granular toggles per notification category.",
    status: "todo",
    priority: "low",
    tags: ["feature", "settings"],
    assignee: jordan,
    createdAt: "2026-06-20T09:00:00.000Z",
    updatedAt: "2026-06-26T09:00:00.000Z",
  },
  {
    id: "8",
    title: "Performance audit",
    description: "Run Lighthouse and optimize critical rendering path",
    notes: "Target a 90+ Lighthouse score on the dashboard route.",
    status: "done",
    priority: "medium",
    tags: ["performance"],
    assignee: alex,
    saved: true,
    subtasks: [
      { id: "8a", title: "Run Lighthouse", done: true },
      { id: "8b", title: "Defer non-critical JS", done: true },
    ],
    createdAt: "2026-06-19T09:00:00.000Z",
    updatedAt: "2026-06-25T09:00:00.000Z",
  },
  {
    id: "9",
    title: "Design notification center",
    description: "Create the slide-over panel for in-app notifications",
    notes: "Group notifications by day and support mark-all-as-read.",
    status: "in_progress",
    priority: "medium",
    tags: ["design", "feature"],
    assignee: jordan,
    dueDate: "2026-07-03T09:00:00.000Z",
    createdAt: "2026-06-18T09:00:00.000Z",
    updatedAt: "2026-06-26T09:00:00.000Z",
  },
  {
    id: "10",
    title: "Refactor auth middleware",
    description: "Simplify session handling and token refresh",
    notes: "Consolidate edge and node middleware into one helper.",
    status: "todo",
    priority: "high",
    tags: ["refactor", "security"],
    assignee: alex,
    dueDate: "2026-07-05T09:00:00.000Z",
    createdAt: "2026-06-17T09:00:00.000Z",
    updatedAt: "2026-06-26T09:00:00.000Z",
  },
  {
    id: "11",
    title: "Build analytics charts",
    description: "Add the productivity and focus-time visualizations",
    notes: "Use a lightweight charting approach to keep bundle small.",
    status: "todo",
    priority: "low",
    tags: ["feature", "analytics"],
    assignee: jordan,
    createdAt: "2026-06-16T09:00:00.000Z",
    updatedAt: "2026-06-26T09:00:00.000Z",
  },
  {
    id: "12",
    title: "Polish onboarding flow",
    description: "Improve the first-run experience and empty states",
    notes: "Add a guided tour and friendly empty-state illustrations.",
    status: "done",
    priority: "medium",
    tags: ["ui", "growth"],
    assignee: alex,
    saved: true,
    createdAt: "2026-06-15T09:00:00.000Z",
    updatedAt: "2026-06-24T09:00:00.000Z",
  },
];
