import type { WorkspaceTask } from "../types";

const activity = [
  { id: "a1", label: "Task assigned to owner", date: "Today, 9:30 AM" },
  { id: "a2", label: "Due date updated", date: "Yesterday, 4:15 PM" },
  { id: "a3", label: "Related CRM record linked", date: "May 18, 2024" },
];

export const workspaceTasks: WorkspaceTask[] = [
  { id: "task-1", title: "Follow up with Apple for proposal", summary: "Overdue 2 days", status: "overdue", priority: "high", assignee: "Alex Morgan", dueDate: "2026-08-18", dueTime: "10:00 AM", relatedTo: "Apple", taskType: "Follow-up", reminder: "Aug 18, 2026 at 9:00 AM", description: "Confirm proposal feedback, align on commercial terms, and document the next decision milestone.", tags: ["Enterprise", "Sales"], subtasks: [{ id: "s1", title: "Review proposal notes", done: true, owner: "Alex Morgan" }, { id: "s2", title: "Send follow-up email", done: false, owner: "Alex Morgan" }], activity, files: [{ id: "f1", name: "acme_proposal.pdf", size: "2.4 MB" }] },
  { id: "task-2", title: "Collect requirements from Google team", summary: "Overdue 1 day", status: "overdue", priority: "high", assignee: "Priya Shah", dueDate: "2026-08-19", dueTime: "11:30 AM", relatedTo: "Google", taskType: "Discovery", reminder: "Aug 19, 2026 at 10:30 AM", description: "Collect technical, security, and reporting requirements from the Google implementation team.", tags: ["Discovery"], subtasks: [{ id: "s3", title: "Share discovery template", done: true, owner: "Priya Shah" }, { id: "s4", title: "Consolidate responses", done: false, owner: "Priya Shah" }], activity, files: [] },
  { id: "task-3", title: "Review contract with Microsoft legal team", summary: "Legal review", status: "overdue", priority: "medium", assignee: "Alex Morgan", dueDate: "2026-08-19", dueTime: "3:00 PM", relatedTo: "Microsoft", taskType: "Legal", reminder: "Aug 19, 2026 at 2:00 PM", description: "Resolve open redlines and confirm the signature sequence with legal stakeholders.", tags: ["Legal"], subtasks: [{ id: "s5", title: "Review redlines", done: false, owner: "Alex Morgan" }], activity, files: [{ id: "f2", name: "initech_contract_v3.pdf", size: "1.8 MB" }] },
  { id: "task-4", title: "Prepare Q3 marketing plan", summary: "Quarterly planning", status: "in_progress", priority: "medium", assignee: "Priya Shah", dueDate: "2026-08-23", dueTime: "5:00 PM", relatedTo: "Amazon", taskType: "Planning", reminder: "Aug 22, 2026 at 10:00 AM", description: "Create and finalize the Q3 marketing plan including campaign strategy, budget allocation, and timeline.", tags: ["Planning", "Q3"], subtasks: [{ id: "s6", title: "Define campaign objectives", done: true, owner: "Priya Shah" }, { id: "s7", title: "Analyze target audience", done: true, owner: "Priya Shah" }, { id: "s8", title: "Create content strategy", done: false, owner: "Alex Morgan" }, { id: "s9", title: "Prepare budget allocation", done: false, owner: "Priya Shah" }, { id: "s10", title: "Review with marketing team", done: false, owner: "Alex Morgan" }], activity, files: [{ id: "f3", name: "q3_campaign_brief.pdf", size: "3.1 MB" }, { id: "f4", name: "budget_model.xlsx", size: "780 KB" }], pinned: true },
  { id: "task-5", title: "Demo product to Pfizer Corp", summary: "Product demo", status: "in_progress", priority: "high", assignee: "Alex Morgan", dueDate: "2026-08-24", dueTime: "2:00 PM", relatedTo: "Pfizer", taskType: "Meeting", reminder: "Aug 24, 2026 at 1:00 PM", description: "Run the tailored enterprise demo and document stakeholder feedback.", tags: ["Demo"], subtasks: [{ id: "s11", title: "Customize demo workspace", done: true, owner: "Alex Morgan" }, { id: "s12", title: "Confirm attendees", done: false, owner: "Alex Morgan" }], activity, files: [] },
  { id: "task-6", title: "Send follow-up email to Tesla", summary: "Email follow-up", status: "in_progress", priority: "low", assignee: "Priya Shah", dueDate: "2026-08-25", dueTime: "9:00 AM", relatedTo: "Tesla", taskType: "Follow-up", reminder: "Aug 25, 2026 at 8:30 AM", description: "Send the workshop recap and proposed next steps to the Tesla team.", tags: ["Email"], subtasks: [], activity, files: [] },
  { id: "task-7", title: "Research new leads in Healthcare", summary: "Market research", status: "todo", priority: "low", assignee: "Alex Morgan", dueDate: "2026-08-27", dueTime: "4:00 PM", taskType: "Research", reminder: "Aug 27, 2026 at 9:00 AM", description: "Identify high-fit healthcare accounts and enrich priority stakeholders.", tags: ["Research"], subtasks: [], activity, files: [] },
  { id: "task-8", title: "Update enterprise pricing sheet", summary: "Internal task", status: "todo", priority: "medium", assignee: "Priya Shah", dueDate: "2026-08-28", dueTime: "12:00 PM", taskType: "Operations", reminder: "Aug 28, 2026 at 10:00 AM", description: "Update packaging assumptions and obtain finance approval.", tags: ["Pricing"], subtasks: [], activity, files: [{ id: "f5", name: "pricing_model.xlsx", size: "920 KB" }] },
  { id: "task-9", title: "Schedule meeting with TechNova", summary: "Intro meeting", status: "todo", priority: "medium", assignee: "Alex Morgan", dueDate: "2026-08-29", dueTime: "1:30 PM", relatedTo: "TechNova Solutions", taskType: "Meeting", reminder: "Aug 29, 2026 at 9:00 AM", description: "Coordinate calendars and share an introduction agenda.", tags: ["Meeting"], subtasks: [], activity, files: [] },
  { id: "task-10", title: "Finalize customer success playbook", summary: "Enablement", status: "completed", priority: "high", assignee: "Priya Shah", dueDate: "2026-08-15", dueTime: "5:00 PM", relatedTo: "Apple", taskType: "Documentation", reminder: "Completed", description: "Publish the enterprise onboarding and adoption playbook.", tags: ["Success"], subtasks: [{ id: "s13", title: "Publish final version", done: true, owner: "Priya Shah" }], activity, files: [{ id: "f6", name: "success_playbook.pdf", size: "4.2 MB" }] },
  { id: "task-11", title: "Complete monthly revenue review", summary: "Finance review", status: "completed", priority: "medium", assignee: "Alex Morgan", dueDate: "2026-08-16", dueTime: "3:00 PM", taskType: "Review", reminder: "Completed", description: "Validate pipeline movements and close the monthly revenue review.", tags: ["Finance"], subtasks: [], activity, files: [] },
  { id: "task-12", title: "Archive closed implementation files", summary: "Operations", status: "completed", priority: "low", assignee: "Priya Shah", dueDate: "2026-08-17", dueTime: "11:00 AM", relatedTo: "Google", taskType: "Operations", reminder: "Completed", description: "Archive completed implementation documents using the records policy.", tags: ["Operations"], subtasks: [], activity, files: [] },
];
